[tools]
node = "24.15.0"
pnpm = "11.1.2"

[tasks.setup]
run = "pnpm i --frozen-lockfile"

[tasks.typecheck]
run = "pnpm run typecheck"

[tasks.lint]
run = "pnpm run lint"

[tasks.build]
run = "pnpm run build:cf"

[tasks.ci]
depends = ["typecheck", "lint", "build"]

[tasks.deploy]
run = "pnpm run deploy"
