name: Lint

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v5

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Lint
        run: pnpm lint
